config/routes.rb
Rails.application.routes.draw do
  
  
  get 'sessions/new'

  root 'static_pages#home'
  
  get '/about',     to: 'static_pages#about'
  get '/services',  to: 'static_pages#services'
  get '/pricing',   to: 'static_pages#pricing'
  
  #users
  get '/signup',    to: 'users#new'
  post '/signup',   to: 'users#create'
  get '/login',     to: 'sessions#new'
  post '/login',    to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :users
  resources :account_activations, only: [:edit]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    attr_accessor :remember_token, :activation_token
    before_save :downcase_email
    before_create :create_activation_digest
    
    
    before_save {email.downcase!}
    validates :name, presence: true, length: {maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true, length: {maximum: 255 },
                      format: {with: VALID_EMAIL_REGEX},
                      uniqueness: {case_sensitive: false}
    validates :password, presence: true, length: {minimum: 6}, allow_nil: true
    has_secure_password
    
    def self.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end
    
    def self.new_token
        SecureRandom.urlsafe_base64
    end
    
    def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
    end
    

    #def authenticated?(remember_token)
        #return false if remember_digest.nil?
        #BCrypt::Password.new(remember_digest).is_password?(remember_token)
    #end
    
    #general authenticated? method
    def authenticated?(attribute, token)
        digest = send("#{attribute}_digest")
        return false if digest.nil?
        BCrypt::Password.new(digest).is_password?(token)
    end
    
    def forget
        update_attribute(:remember_digest, nil)
    end
    
    def create_activation_digest
       self.activation_token = User.new_token
       self.activation_digest = User.digest(activation_token)
    end
    
    def activate 
        update_attribute(:activated, true)
        update_attribute(:activated_at, Time.zone.now)
    end
    
    def send_activation_email
        UserMailer.account_activation(self).deliver_now
    end
    
    private
    
        def downcase_email
            self.email = email.downcase
        end
end

app/controllers/account_activations_controller.rb
class AccountActivationsController < ApplicationController
    
    def edit
    user = User.find_by(email: params[:email])
        if user && !user.activated? && user.authenticated?(:activation, params[:id])
            user.activate
            #user.update_attribute(:activated, true)
            #user.update_attribute(:activated_at, Time.zone.now)
            log_in user
            flash[:success] = "Account Activated!"
            redirect_to user
        else
            flash[:danger] = "Invalid activation link"
            redirect_to root_url
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  
   before_action :detect_device_variant
  
  private
    
  def detect_device_variant
    request.variant = :phone if browser.device.mobile?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      if user.activated?
        log_in user
        params[:session][:remember_me] == '1' ? remember(user) : forget(user) 
        redirect_back_or user
      else
        message = "Acocunt not activated. Check your email for activation link."
        flash[:warning] = message
        redirect_to root_url
      end
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end
  
  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @disable_header = true
  end

  def about
  end
  
  def pricing
  end
  
  def services
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy
  
  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      #UserMailer.account_activation(@user).deliver_now
      flash[:info] = "Please check your email to activate your account"
      redirect_to root_url 
    else
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile Updated!"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User Deleted"
    redirect_to users_url
  end
  
  private
    
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
    
    #Before filters
    
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in to continue"
        redirect_to login_url
      end
    end
    
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
    
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/account_activations_helper.rb
module AccountActivationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    # Returns title of page
    def full_title(page_title = '')
        base_title = "Social Curate"
        if page_title.empty?
            base_title
        else
            base_title + " | " + page_title
        end
    end
    
end

app/helpers/sessions_helper.rb
module SessionsHelper
    
    def log_in(user)
        session[:user_id] = user.id
    end
    
    def remember(user)
        #this is a class method(implied by the way it's called)
        user.remember
        cookies.permanent.signed[:user_id] = user.id
        cookies.permanent[:remember_token] = user.remember_token
    end
    
    # returns true if given user is current user
    def current_user?(user)
        user == current_user
    end  
    
    # returns user corresponding to the remember token cookie    
    def current_user
        if (user_id = session[:user_id])
            @current_user ||= User.find_by(id: user_id)
        elsif (user_id = cookies.signed[:user_id])
            user = User.find_by(id: user_id)
            if user && user.authenticated?(:remember, cookies[:remember_token])
                log_in user
                @current_user = user
            end
        end
    end
    
    def logged_in?
        !current_user.nil?
    end
    
    
    def forget(user)
        user.forget
        cookies.delete(:user_id)
        cookies.delete(:remember_token)
    end
    
    def log_out
        forget(current_user)
        session.delete(:user_id)
        @current_user = nil
    end
    
    # Redirects to stored location (or to the default).
    def redirect_back_or(default)
        redirect_to(session[:forwarding_url] || default)
        session.delete(:forwarding_url)
    end

    # Stores the URL trying to be accessed.
    def store_location
        session[:forwarding_url] = request.original_url if request.get?
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
    
    #gravatar
    def gravatar_for(user, options = {size: 80})
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
    
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" id="header-button" data-toggle="collapse" data-target="#myNavbar">
        <%= image_tag('menu.png', size: '44x44') %>
      </button>
      
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <div class="center">
        <ul class="nav navbar-nav">
        
          <li><%= link_to "Home", root_path, method: :get, class: "header-logo" %></li>
          <li><%= link_to "About", about_path, method: :get, class: "header-logo" %></li>
          <li><%= link_to "Pricing", '#', class: "header-logo" %></li>
          
           <% if logged_in? %>
            <li><%= link_to "Users", users_path, class: "header-logo" %></li>
            <li><%= link_to 'Account', current_user, class: "header-logo" %></li>
            <li><%= link_to "Settings", edit_user_path(current_user), class: "header-logo" %></li>
            <li><%= link_to "Log out", logout_path, method: :delete, class: "header-logo" %></li>
          <% else %>
            <li><%= link_to "Log in", login_path, class: "header-logo" %></li>
          <% end %>
          
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  
  <meta property="og:type"          content="website" />
  <meta property="og:title"         content="Moon|Half" />
  <meta property="og:description"   content="Web Development Blog" />
  <meta property="og:image"         content="assets/moonicon.png" />
  <meta property="og:image" content="#{image_url('preloader.gif')}" />
  
  <meta name="viewport" content="width=device-width; height=device-height; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">
  <%= favicon_link_tag 'preloader.gif' %>
  
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
    <![endif]-->
    
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                'data-turbolinks-track': 'reload'%>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <%= render 'layouts/header' unless @disable_header %>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/parallax/3.1.0/parallax.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js"></script>
  </head>
  
  
    <body>
      <div class="container">
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
      </div>
      
       <%= yield %>
    </body>
    
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
    
    
    <script>
    
      
      /* Preloader */
      $(document).ready(function () {
        $(window).load(function(){
          $('#preloader').delay(400).fadeOut(500);
        })
      })
      
      /* AOS Init */
      AOS.init();
      
      function fadeInPartial(ele) {
        ele.style.opacity = '0.89';
      }
    </script>
    
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC" rel="stylesheet">
    
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-danger">
            The form contains <%= pluralize(@user.errors.count, 'error') %>
        </div>
        
        <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li>
                    <%= msg %>
                </li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/static_pages/about.html.erb
<div class="center"></div>


<div class="row-centered">
    <div class="col-md-2"></div>
    <div class="col-md-8 col-centered">
        <div class="padding-block">
        <div class="text-box-general">
            <h1 class="gold header-logo">
                Do you hate posting, writing captions, and responding to comments and messages? Don't worry, a lot of people do,
                and thats why we created SocialCurate.com! Social media is a necessary part of advertising in the modern world,
                but the truth is there are some people that just don't like spending that much time using it. That's why we're here.
                We create and curate socail media accounts for both business and personal use on a weekly basis. 
            </h1>
            <%= link_to '#' do %>
                <h1 class="gold header-logo">Sign Up!</h1>
            <% end %>
        </div>
        </div>
    </div>
    <div class="col-md-2"></div>
</div>

<script>
document.addEventListener("DOMContentLoaded", function() {
    var textBox = document.querySelector('.text-box-general');
    
    setTimeout(function() {fadeInPartial(textBox)}, 500);
});
</script>

app/views/static_pages/home.html+phone.erb
<body class="mobile-home">
<div id="preloader">
  <div id="status">&nbsp;</div>
</div>
<div class="center">
    
<div id="scene">
<div class="layer" data-depth="0.6"> 

    <div class="row">
        <h1 class="mobile-logo">Social Curate</h1>
    </div>

</div>
</div>
    
    &nbsp;
    <div class="row">
        <div class="col-xs-6">
            <div class="mobile-box" id="mobile-box1">
                <h1 class="mobile-logo">Services</h1>
                <%= link_to services_path, class: 'gold', method: :get do %>
                    <button class="mobile-button">Click Here</button>
                <% end %>
            </div>    
        </div>
        
        <div class="col-xs-6">
            <div class="mobile-box" id="mobile-box2">
                <h1 class="mobile-logo">About</h1>
                <%= link_to about_path, class: 'gold', method: :get do %>
                    <button class="mobile-button">Click Here</button>
                <% end %>
            </div>    
        </div>
   </div>
    &nbsp;
    
    <div class="row">
        <div class="col-xs-6">
            <div class="mobile-box" id="mobile-box3">
                <h1 class="mobile-logo">Pricing</h1>
                <%= link_to pricing_path, class: 'gold', method: :get do %>
                    <button class="mobile-button">Click Here</button>
                <% end %>
            </div>    
        </div>
        
       <div class="col-xs-6">
            <div class="mobile-box" id="mobile-box4">
                <h1 class="mobile-logo">Contact</h1>
                <a href="mailto:christian.c.orourke@gmail.com?subject=Social%20Curate" target="_blank" class='gold'><button class="mobile-button">Send me an email!</button></a>
            </div>    
        </div>
    </div>
    &nbsp;
    <div class="row">
        
        <%= link_to signup_path, class: 'gold', method: :get do %>
            <button class="mobile-button-lg">Signup/Login</button>
        <% end %>
       
    </div>
    
</div>    
    
</body>

<script>
    // Initialize Parallax.js
      var scene = document.getElementById('scene');
      var parallax = new Parallax(scene);
</script>

app/views/static_pages/home.html.erb
<body id="home">


<div class="panels">
    
  <div class="panel panel1 secTransition">
    <p></p>
    <p>Services</p>
    <p>
      <%= link_to services_path, method: :get do %>
        <button>Click Here</button>
      <% end %>    
    </p>
  </div>
    
  <div class="panel panel2 secTransition">
    <p>About Info</p>
    <p>About</p>
    <p>
      <%= link_to about_path, method: :get do %>
        <button>Click Here</button>
      <% end %>
    </p>
  </div>
    
  <div class="panel panel3 secTransition">
    <p></p>
    <p>Social Curate</p>
    <p>
      <%= link_to signup_path, method: :get do %>
        <button>Signup/Login</button>
      <% end %>    
    </p>
  </div>
    
  <div class="panel panel4 secTransition">
    <p>Pricing Info</p>
    <p>Pricing</p>
    <p>
      <%= link_to pricing_path, method: :get do %>
        <button>Click Here</button>
      <% end %>
    </p>
  </div>
    
  <div class="panel panel5 secTransition">
    <p></p>
    <p>Contact</p>
    <p><a href="mailto:christian.c.orourke@gmail.com?subject=Social%20Curate" target="_blank"><button>Send me an email!</button></a></p>
  </div>

</div>
</body>

<script>
document.addEventListener("DOMContentLoaded", function() {
  
  var p1 = document.querySelector('.panel1');
  var p2 = document.querySelector('.panel2');
  var p3 = document.querySelector('.panel3');
  var p4 = document.querySelector('.panel4');
  var p5 = document.querySelector('.panel5');


  const panels = document.querySelectorAll('.panel');
    
  function toggleOpen() {
    this.classList.toggle('open');
  }
    
  function toggleActive(event) {
    if (event.propertyName.includes('flex')) {
      this.classList.toggle('open-active');
    }
  }
    
  panels.forEach(panel => panel.addEventListener('click', toggleOpen));
  panels.forEach(panel => panel.addEventListener('transitionend', toggleActive));
    
  //fade in panels
  function fadeIn(ele) {
    ele.style.opacity = '1.0';
  }
  
  // remove longer transoition time
  function removeTransition(ele) {
    ele.classList.remove('secTransition');
  }
  
  setTimeout(function() {fadeIn(p1)}, 1000);
  setTimeout(function() {fadeIn(p2)}, 1700);
  setTimeout(function() {fadeIn(p3)}, 2400);
  setTimeout(function() {fadeIn(p4)}, 3100);
  setTimeout(function() {fadeIn(p5)}, 3800);
  
  // remove longer transition time from all panels
  panels.forEach(panel => setTimeout(function() {removeTransition(panel)}, 3801));
});
</script>

app/views/static_pages/services.html.erb
<div id="preloader">
  <div id="status">&nbsp;</div>
</div>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit User") %>
<h1>Update your profile</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages' %>
        
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>
        
            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control' %>
        
            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control' %>
        
            <%= f.label :password_confirmation %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
            
            <%= f.submit "Save Changes", class: 'form-control' %>
        
        <% end %>
     
        <div class="gravatar-edit">
            <%= gravatar_for(@user) %>
            <a href="http://gravatar.com/emails" target="_blank" rel="noopener">change</a>
        </div>
        
    </div>
</div>

app/views/users/index.html.erb
<%= provide(:title, "Users") %>

<h1>Users</h1>

<%= will_paginate %>

<%= render @users %>

<%= will_paginate %>

app/views/users/new.html.erb
#https://www.railstutorial.org/book/account_activation#code-signup_with_account_activation_test

<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages' %>
    
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>